no.nav:
  kafka:
    security:
      protocol: SSL
      ssl:
        key-password: ${KAFKA_CREDSTORE_PASSWORD}
        trust-store-type: JKS
        trust-store-location: file:${KAFKA_TRUSTSTORE_PATH}
        trust-store-password: ${KAFKA_CREDSTORE_PASSWORD}
        key-store-location: file:${KAFKA_KEYSTORE_PATH}
        key-store-password: ${KAFKA_CREDSTORE_PASSWORD}
        key-store-type: PKCS12
    schema-registry:
      url: ${KAFKA_SCHEMA_REGISTRY_URL}
      username: ${KAFKA_SCHEMA_REGISTRY_USER}
      password: ${KAFKA_SCHEMA_REGISTRY_PASSWORD}
    streams:
      psb-soknad-preprosessering:
        auto-offset-reset: none
      psb-soknad-journalforing:
        auto-offset-reset: none
      psb-soknad-cleanup:
        auto-offset-reset: none

      psb-endringsmelding-preprosessering:
        auto-offset-reset: none
      psb-endringsmelding-journalforing:
        auto-offset-reset: none
      psb-endringsmelding-cleanup:
        auto-offset-reset: none
